---
# Source: acuity-bkstg/charts/ingress-nginx/templates/controller-poddisruptionbudget.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    helm.sh/chart: ingress-nginx-3.35.0
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "0.48.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: RELEASE-NAME-ingress-nginx-controller
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/instance: RELEASE-NAME
      app.kubernetes.io/component: controller
  minAvailable: 1
