apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.api.name }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
      # since we are using dyamic IPs, and nip.io for a reflected (any dynamic) DNS,
      # use the lookup function to determine the domain name serving this app
      - {{ .Values.api.name}}.{{ (lookup "v1" "Service" "ingress" "ingress-nginx").externalIP }}.nip.io 
      secretName: {{ .Values.api.name }}-cert
  rules:
    # since we are using dyamic IPs, and nip.io for a reflected (any dynamic) DNS,
    # use the lookup function to determine the domain name serving this app
    host: {{ .Values.api.name}}.{{ (lookup "v1"  "Service" "ingress" "ingress-nginx").externalIP }}.nip.io
    http:
      paths:
      - backend:
          serviceName: {{ .Values.api.name }}
          servicePort: 80
        path: /