apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.api.name }}
immutable: true
data:
  app-config.yaml: |-
    app:
      title: {{ .Values.app.name }}
      baseUrl: {{ .Values.app.baseUrl }}

    organization:
      name: {{ .Values.organization.name }}

    backend:
      baseUrl: {{ .Values.api.baseUrl }}
      listen:
        port: {{ .Values.api.port }}
      database:
        {{ .Values.api.database | toYaml |  indent 8 | trim }}
      cache:
        {{ toYaml .Values.api.cache | indent 8 | trim }}
    catalog:
      locations: []
    # Reference documentation http://backstage.io/docs/features/techdocs/configuration
    # Note: After experimenting with basic setup, use CI/CD to generate docs
    # and an external cloud storage when deploying TechDocs for production use-case.
    # https://backstage.io/docs/features/techdocs/how-to-guides#how-to-migrate-from-techdocs-basic-to-recommended-deployment-approach
    techdocs:
      builder: 'local' # Alternatives - 'external'
      generator:
        runIn: 'docker' # Alternatives - 'local'
      publisher:
        type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.
    auth:
      # see https://backstage.io/docs/auth/ to learn about auth providers
      providers: {}
    scaffolder:
      github:
        token: ${GITHUB_TOKEN}
        visibility: public # or 'internal' or 'private'
    catalog:
      rules:
        - allow: [Component, System, API, Group, User, Resource, Location]
      locations:
        # Backstage example components
        - type: url
          target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-components.yaml

        # Backstage example systems
        - type: url
          target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-systems.yaml

        # Backstage example APIs
        - type: url
          target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-apis.yaml

        # Backstage example resources
        - type: url
          target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-resources.yaml

        # Backstage example organization groups
        - type: url
          target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme/org.yaml

        # Backstage example templates
        - type: url
          target: https://github.com/backstage/software-templates/blob/main/scaffolder-templates/react-ssr-template/template.yaml
          rules:
            - allow: [Template]
        - type: url
          target: https://github.com/backstage/software-templates/blob/main/scaffolder-templates/springboot-grpc-template/template.yaml
          rules:
            - allow: [Template]
        - type: url
          target: https://github.com/spotify/cookiecutter-golang/blob/master/template.yaml
          rules:
            - allow: [Template]
        - type: url
          target: https://github.com/backstage/software-templates/blob/main/scaffolder-templates/docs-template/template.yaml
          rules:
            - allow: [Template]

